#!/bin/bash

## Script autogenerated by GPT-3.5 piece by piece and then modified to suit our needs

echo "Attempting to invoke openssl generation of self signed cert."

if ! command -v openssl &> /dev/null; then
    echo "Error: openssl not found. Please install openssl before running this script."
    exit 1
fi

############################################################################################################
# Options explanation (generated by GPT-3.5)                                                               #
#                                                                                                          #
# Generate a self-signed SSL certificate and private key using OpenSSL                                     #
# -x509: Create a self-signed certificate instead of a certificate signing request (CSR).                  #
# -newkey rsa:4096: Generate a new RSA private key with a length of 4096 bits.                             #
# -keyout <filename>.pem: Specify the file to which the private key should be written.                     #
# -out <filename>.pem: Specify the file to which the self-signed certificate should be written.            #
# -days 365: Set the validity period of the certificate to 365 days.                                       #
# -nodes: Create the private key without encrypting it with a passphrase (not recommended for production). #
############################################################################################################

## Invoke openssl to generate the private key and cert in .pem format
openssl req -x509 -newkey rsa:4096 -keyout private_key.pem -out certificate.pem -days 365 -nodes -subj "/CN=localhost"

## Convert the key and cert pem files into a passwordless .pfx file
openssl pkcs12 -export -out praxis.pfx -inkey private_key.pem -in certificate.pem -passout pass:

## Clean up the .pem files, they're not needed regardless of the success or failure of the previous command
rm private_key.pem; rm certificate.pem;

if [ -e "praxis.pfx" ]; then
    echo "Created praxis.pfx successfully in present working directory.";
    echo "Quitting..."
    exit 0
else
    echo "Unable to generate the pfx file. Aborting."
    exit 1
fi






# echo "Wrote praxis_key.pem and praxis_cert.pem to present working directory"



