#!/bin/bash

## Portions of this script were autogenerated by GPT-3.5

echo "Attempting to invoke openssl generation of self signed cert."

if ! command -v openssl &> /dev/null; then
    echo "Error: openssl not found. Please install openssl before running this script."
    exit 1
fi

############################################################################################################
# Options explanation (generated by GPT-3.5)                                                               #
#                                                                                                          #
# Generate a self-signed SSL certificate and private key using OpenSSL                                     #
# -x509: Create a self-signed certificate instead of a certificate signing request (CSR).                  #
# -newkey rsa:4096: Generate a new RSA private key with a length of 4096 bits.                             #
# -keyout <filename>.pem: Specify the file to which the private key should be written.                     #
# -out <filename>.pem: Specify the file to which the self-signed certificate should be written.            #
# -days 365: Set the validity period of the certificate to 365 days.                                       #
# -nodes: Create the private key without encrypting it with a passphrase (not recommended for production). #
############################################################################################################

openssl req -x509 -newkey rsa:4096 -keyout praxis_key.pem -out praxis_cert.pem -days 3650 -nodes

echo "Wrote praxis_key.pem and praxis_cert.pem to present working directory"
exit 0


